# Generated by Django 4.2.5 on 2023-10-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_passsword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('app_type', models.CharField(max_length=100)),
                ('website_name', models.CharField(blank=True, max_length=100)),
                ('website_url', models.CharField(blank=True, max_length=100)),
                ('application_name', models.CharField(blank=True, max_length=50)),
                ('game_name', models.CharField(blank=True, max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
